// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqfukushsiyotqwsouoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxZnVrdXNoc2l5b3Rxd3NvdW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTkyNTAsImV4cCI6MjA2NTU5NTI1MH0.NnaeSTHUBo35VjH7Ehn5_omY7uBJu_uKp5LfMkM7NnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);